export const GENERAL_TEXT = {
    NEW_LIST: "Checkout New List",
    PROGRAMMING_LANGUAGE: "Programming Language",
    ADD_COURSE: "Add Course",
    EDIT_COURSE: "Edit Course",
    ADD: "Add",
    EDIT: "Edit",
    CANCEL: "Cancel",
    DURATION: "Duration",
    LEVEL: "Level",
    STUDENTS: "Students",
    RATING: "Rating",
    OVERVIEW: "Overview",
    ABOUR_INSTRUCTOR: "About the Instructor",
    COURSE_TITLE: "Course Title",
    DESCRIPTION: "Description",
    INSTRUCTOR_NAME: "Instructor Name",
    INSTRUCTOR_EMAIL: "Instructor Email",
    STUDENTS_NUMBER: "Number of Students",
    PRICE: "Price",
    TAGS: "Tags",
    TAG_NAME: "Tag Name",
    TAG_DESCRIPTION: "Tag Description",
}